### ISSUE TITLE
Trouble with authType webflow

### ISSUE THREAD

**Issue by crob27** [gnojus/nec#2]
Hi,

I get an error when I do this :

$ /home/steph/download/nec-linux-amd64 share 4eme_Pyramides_et_cones_exercice_38_page_243.mp4 
Error: parsing config: incomplete account information: {user: pass: url:https://my_server_on_the_net/nextcloud}

My ~/.config/Nextcloud/nextcloud.cfg contains

[Accounts]
...
0\authType=webflow
...
0\url=https://my_server_on_the_net/nextcloud
0\user=@Invalid()
0\webflow_user=my_user

And there isn't any "pass" line.
Nextcloud client is running in xfce using debian bullseye.

Is there a solution ?

Regards.

**Comment by gnojus** [comment]
Hi,
interesting. `pass` should be empty here (it's fetched later from keyring), but empty `user` is the problem here.

I added a fallback to `webflow_user`, could you try `v0.1.3` to see if the problem is fixed? (`nec update` or download from releases).

**Comment by crob27** [comment]
Hi,
It solves the error, but it doesn't seem to access nextcloud server.
I get 

$ /home/steph/download/nec-linux-amd64-1.0.3 share 4eme_Pyramides_et_cones_exercice_38_page_243.mp4
Error: file /home/steph/Docs/maths_videos/4eme_Pyramides_et_cones_exercice_38_page_243.mp4 is not synced by any account

$ /home/steph/download/nec-linux-amd64-1.0.3 share fonctions_affines_exercice_45_page_156.mp4
Error: file /home/steph/Docs/maths_videos/fonctions_affines_exercice_45_page_156.mp4 is not synced by any account

Those two files are on the server.

Regards.

**Comment by gnojus** [comment]
Could you please provide full nextcloud.cfg?
Or at least lines starting with `<ID>/Folders`.

I should really add better debugging output, though,

**Comment by crob27** [comment]
[General]
confirmExternalStorage=true
newBigFolderSizeLimit=500
optionalServerNotifications=true
useNewBigFolderSizeLimit=true

[Accounts]
0\Folders\1\ignoreHiddenFiles=false
0\Folders\1\journalPath=._sync_azertyuio1234.db
0\Folders\1\localPath=/mnt/sda/steph/photos/
0\Folders\1\paused=false
0\Folders\1\targetPath=/Photos/Famille
0\Folders\2\ignoreHiddenFiles=false
0\Folders\2\journalPath=._sync_qwertyuio1234.db
0\Folders\2\localPath=/home/www/html/steph/mes_dessins/
0\Folders\2\paused=false
0\Folders\2\targetPath=/Dessins/croquis
0\authType=webflow
0\serverVersion=24.0.4.1
0\url=https://my_server_on_the_net/nextcloud
0\user=@Invalid()
0\webflow_user=XXXXXXXXXX
1\Multifolders\3\ignoreHiddenFiles=false
1\Multifolders\3\journalPath=._sync_abcdef123.db
1\Multifolders\3\localPath=/home/steph/Docs/maths/
1\Multifolders\3\paused=false
1\Multifolders\3\targetPath=/maths
1\Multifolders\4\ignoreHiddenFiles=false
1\Multifolders\4\journalPath=._sync_ghijk1234.db
1\Multifolders\4\localPath=/home/steph/Docs/maths_videos/
1\Multifolders\4\paused=false
1\Multifolders\4\targetPath=/maths_videos
1\authType=webflow
1\serverVersion=24.0.7.1
1\url=https://nuage03.apps.education.fr
1\user=@Invalid()
1\webflow_user=XXXXXXXXXX
version=2

**Comment by gnojus** [comment]
OK, I have not seen `Multifolders` before.
Will have a look at this.

**Comment by gnojus** [comment]
Released 0.1.4, should now support Multifolders.

**Comment by crob27** [comment]
Hi
You're right. It works.
It will be a lot faster to get share links.
Regards.

**Comment by gnojus** [comment]
glad to hear that
