### ISSUE TITLE
file is not synced by any account

### ISSUE THREAD

**Issue by szymontex** [gnojus/nec#3]
In CMD:
C:\IT>nec-windows-amd64.exe s C:\Users\<my user name>\Nextcloud\<drive folder>\<filename>.jpg

Error: file C:\Users\<my user name>\Nextcloud\<drive folder>\<filename>.jpg is not synced by any account

What is correct path for it to work?

**Comment by gnojus** [comment]
The path must point to a file/folder that is synced by the desktop Nextcloud client (relative or absolute should both work). If it doesn't, could you share your nextcloud.cfg (should be in `%appdata%/Nextcloud`). Thanks

**Comment by szymontex** [comment]
@gnojus  0\FoldersWithPlaceholders\1\localPath=   
That line?
or 0\FoldersWithPlaceholders\1\targetPath=/

**Comment by gnojus** [comment]
I think it's localPath. 

I wanted the full config file (you can leave out sensitive parts such as username or url), but what you wrote should work as well, as I have not seen `FoldersWithPlaceholders` before and that's not intergrated into *nec* yet.

Will take a look at it, shouldn't be too hard to fix.

**Comment by gnojus** [comment]
Can you try **v0.1.5** (run `nec update` or download new version from releases).

**Comment by szymontex** [comment]
Full .cfg

[General]
clientVersion=3.9.0stable-Win64 (build 20230613)
overrideLocalDir=
overrideServerUrl=
updateSegment=79
optionalServerNotifications=false
showCallNotifications=false
showInExplorerNavigationPane=false
confirmExternalStorage=false
crashReporter=true
isVfsEnabled=false
monoIcons=true
newBigFolderSizeLimit=500
useNewBigFolderSizeLimit=false

[Accounts]
version=2
0\version=1
0\url=<<nextcloud_server_url>>
0\dav_user=<<nextcloud_user>>
0\serverVersion=26.0.0.11
0\webflow_user=<<nextcloud_user>>
0\authType=webflow
0\user=@Invalid()
0\displayName=<<nextcloud_user>>
0\FoldersWithPlaceholders\1\localPath=C:/Users/<<my_windows_user_name>>/Nextcloud/
0\FoldersWithPlaceholders\1\journalPath=.sync_232ac98d3d00.db
0\FoldersWithPlaceholders\1\targetPath=/
0\FoldersWithPlaceholders\1\paused=false
0\FoldersWithPlaceholders\1\ignoreHiddenFiles=false
0\FoldersWithPlaceholders\1\virtualFilesMode=wincfapi
0\FoldersWithPlaceholders\1\version=3
0\FoldersWithPlaceholders\1\navigationPaneClsid=@Variant(\0\0\0\x7f\0\0\0\x6QUuid\0Z\xbf|\x92\x1e\xb5M\xef\x86}Z\x9aZ\xe6\x8eJ)

[Proxy]
type=2

[Settings]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x5\xb5\0\0\x1|\0\0\a\xba\0\0\x3\xde\0\0\x5\xb6\0\0\x1\x9b\0\0\a\xb9\0\0\x3\xdd\0\0\0\0\0\0\0\0\rp\0\0\x5\xb6\0\0\x1\x9b\0\0\a\xb9\0\0\x3\xdd)

[Nextcloud]
autoUpdateCheck=false

**Comment by szymontex** [comment]
PERFECT, v0.1.5 works! Thank you mate!
